### PR TITLE
Added bower support

### PR DESCRIPTION
**Pull request by benschwarz**
selectivizr is already IN the bower repository — accepting this pull request will make users of bower & selectivizr happy. 

Bower uses tags, so as per #67, it'd be great if you could

`git tag 1.0.3` 

After accepting this pull request (or use the new github releases feature).

Lemme know if you have any questions, I'll do my best to answer.

This will close Ref: #62 when merged.

### CODE REVIEW

**Comment by benschwarz** [comment]
ping @keithclark

**Comment by jamesscholeyweb** [comment]
for the time being you can add selectivizr by the latest commit in bower.json

"selectivizr": "git://github.com/keithclark/selectivizr#ed2f5e3e56f059ad256cc921e24ecc0e1855f18a"

it might state that it has resolved to 1.0.2 but if you check the file it should be 1.0.3b

same issue as #67

**Comment by benschwarz** [comment]
I didn't think that bower worked with SHAs… ?

**Comment by jamesscholeyweb** [comment]
Hi Ben, this was bugging me all day, after a bit of reading it seemed bower had now merged the ability to specify commits so I tried it. I'm using a yeoman-generator, but although it gives a little warning message saying it's resolving to 1.0.2-14 when I check my bower_components it has pulled in 1.0.3b and grunt-usemin parses the file no probs. So a working solution until keith pushes the 1.0.3 and updates bower.

**Comment by benschwarz** [comment]
Ahhhh, righto. I haven't bothered to update my bower version yet! Thanks for the info.

**Comment by jpdevries** [comment]
+1

**Pull request closed without merging**
