### PR TITLE
No longer used to determine the version of IE userAgent. 

### PR DESCRIPTION
**Pull request by gucong3000**
No longer used to determine the version of IE userAgent. 
No longer deal with the absolute path of the background image.

### CODE REVIEW

**Comment by gucong3000** [comment]
userAgent not reliable, do not use it in this way determine the version of IE.
Also, in addition to base64 format other than an absolute path does not need to deal with the background image

**Comment by keithclark** [comment]
I can't review this because the entire file has changed.

**Comment by gucong3000** [comment]
Done. Only my changes now.

**Comment by zamber** [comment]
Still the whole file is changed probably because of end of line characters. gucong3000 read https://help.github.com/articles/dealing-with-line-endings and apply the fixes again on a clean fork.

**Pull request closed without merging**
